# Generated by Django 5.1.2 on 2024-12-01 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_movie_cast_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('quality', models.CharField(choices=[('HD', 'HD'), ('SD', 'SD')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_links', to='accounts.movie')),
            ],
            options={
                'unique_together': {('movie', 'quality')},
            },
        ),
    ]
